---
- name: Set sysctl.conf for pja 1
  lineinfile:
    dest: '{{ config_file.set_sysctl }}'
    create: yes
    regexp: '^{{item.key}}'
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - "{{ set_sysctl }}"
  register: set_sysctl_result

- name: Set sysctl.conf for mpn 2 +++run shell sysctl+++  +++run skipping when sysctl already be set+++
  shell:  /usr/sbin/sysctl -p '{{ config_file.set_sysctl }}'
  when: set_sysctl_result.changed == true

